create table news
(
    id              bigint generated by default as identity
        constraint news_pk
            primary key,
    heading         varchar,
    body            varchar,
    url             varchar,
    date            varchar,
    country         varchar,
    interview       boolean,
    verified_source boolean
);